(()=>{
  const ready=fn=>document.readyState==='loading'?document.addEventListener('DOMContentLoaded',fn,{once:true}):fn();
  ready(async()=>{
    if(!window.supabase||!window.JEEBLI_CONFIG||!/\/admin\.html$/i.test(location.pathname))return;
    const dbAreas=window.supabase.createClient(window.JEEBLI_CONFIG.SUPABASE_URL,window.JEEBLI_CONFIG.SUPABASE_KEY);
    const q=id=>document.getElementById(id);
    const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#039;'}[c]));
    const kindLabel={district:'قضاء',subdistrict:'ناحية / مركز',village:'قرية / منطقة',neighborhood:'حي'};
    let areas=[];let editId=null;let map=null;let marker=null;

    function toast(msg){if(typeof window.notify==='function')window.notify(msg);else alert(msg)}
    function addStyle(){if(document.querySelector('link[href="./admin-areas.css"]'))return;const l=document.createElement('link');l.rel='stylesheet';l.href='./admin-areas.css';document.head.appendChild(l)}
    function ensureLeaflet(){return new Promise(resolve=>{if(window.L)return resolve();if(!document.querySelector('link[data-area-leaflet]')){const l=document.createElement('link');l.rel='stylesheet';l.href='https://unpkg.com/leaflet@1.9.4/dist/leaflet.css';l.dataset.areaLeaflet='1';document.head.appendChild(l)}const existing=document.querySelector('script[data-area-leaflet]');if(existing){existing.addEventListener('load',()=>resolve(),{once:true});setTimeout(()=>window.L&&resolve(),50);return}const s=document.createElement('script');s.src='https://unpkg.com/leaflet@1.9.4/dist/leaflet.js';s.dataset.areaLeaflet='1';s.onload=()=>resolve();document.body.appendChild(s)})}

    addStyle();
    const nav=document.querySelector('.sidebar nav');
    const supportNav=nav?.querySelector('[data-section="support"]');
    if(nav&&!q('areasNavBtn')){
      const b=document.createElement('button');b.id='areasNavBtn';b.className='nav-item';b.innerHTML='<i data-lucide="map-pinned"></i><span>المناطق والقرى</span>';nav.insertBefore(b,supportNav||null);
      b.onclick=()=>openAreasSection();
    }

    const content=document.querySelector('.content');
    const supportSection=q('section-support');
    if(content&&!q('section-areas')){
      const section=document.createElement('section');section.id='section-areas';section.className='admin-section';section.innerHTML=`
        <div class="section-actions"><div><p class="kicker">تغطية جيبلي</p><h2>المناطق والقرى</h2><p class="muted">إدارة قضاء الشرقاط والنواحي والقرى. أي تعديل هنا ينعكس على التسجيل وتوزيع السائقين.</p></div><button id="addAreaBtn" class="btn primary"><i data-lucide="map-pin-plus"></i> إضافة منطقة</button></div>
        <div class="areas-stats"><article class="area-stat"><small>الإجمالي</small><strong id="areaStatAll">0</strong></article><article class="area-stat"><small>الأقضية</small><strong id="areaStatDistrict">0</strong></article><article class="area-stat"><small>النواحي</small><strong id="areaStatSubdistrict">0</strong></article><article class="area-stat"><small>القرى والمناطق</small><strong id="areaStatVillage">0</strong></article></div>
        <section class="panel"><div class="areas-toolbar"><input id="areaSearch" class="control search" type="search" placeholder="بحث باسم القضاء أو الناحية أو القرية"/><select id="areaTypeFilter" class="control"><option value="all">كل الأنواع</option><option value="district">الأقضية</option><option value="subdistrict">النواحي</option><option value="village">القرى والمناطق</option><option value="neighborhood">الأحياء</option></select><button id="refreshAreasBtn" class="btn soft">تحديث</button></div><div id="areasTree" class="areas-tree"></div></section>`;
      content.insertBefore(section,supportSection||null);
      q('addAreaBtn').onclick=()=>openModal();q('refreshAreasBtn').onclick=loadAreas;q('areaSearch').oninput=render;q('areaTypeFilter').onchange=render;
    }

    if(!q('areaModal')){
      const modal=document.createElement('div');modal.id='areaModal';modal.className='modal hidden';modal.innerHTML=`<div class="modal-card area-modal-card"><div class="modal-head"><div><p class="kicker">منطقة التغطية</p><h2 id="areaModalTitle">إضافة منطقة</h2></div><button id="closeAreaModal" class="close-btn">×</button></div><form id="areaForm" class="stack-form"><div class="area-modal-grid"><label>الاسم بالعربي<input id="areaName" required placeholder="مثال: الهيجل"/></label><label>النوع<select id="areaType" required><option value="district">قضاء</option><option value="subdistrict">ناحية / مركز</option><option value="village" selected>قرية / منطقة</option><option value="neighborhood">حي</option></select></label><label class="wide">يتبع إلى<select id="areaParent"><option value="">بدون أب</option></select></label><label>خط العرض<input id="areaLat" type="number" step="any" placeholder="اختياري"/></label><label>خط الطول<input id="areaLng" type="number" step="any" placeholder="اختياري"/></label><label>ترتيب الظهور<input id="areaSort" type="number" value="0"/></label><label class="check-line"><input id="areaActive" type="checkbox" checked/><span>مفعلة داخل التطبيق</span></label><label class="wide">ملاحظة / مصدر<textarea id="areaSource" rows="2" placeholder="اختياري"></textarea></label><div class="wide"><div id="areaMap" class="area-map"></div><p class="area-source-note">اضغط على الخريطة لتحديد مركز المنطقة تقريبياً. الإحداثيات تساعد الإدارة على المتابعة وتطوير فلترة GPS لاحقاً.</p></div></div><div class="area-delete-note">حذف ناحية أو قضاء يحتوي عناصر تابعة سيُمنع لحماية البيانات. انقل أو احذف العناصر التابعة أولاً.</div><div class="form-actions"><button id="cancelAreaBtn" type="button" class="btn soft">إلغاء</button><button type="submit" class="btn primary">حفظ المنطقة</button></div></form></div>`;document.body.appendChild(modal);
      q('closeAreaModal').onclick=closeModal;q('cancelAreaBtn').onclick=closeModal;q('areaForm').onsubmit=saveArea;modal.onclick=e=>{if(e.target===modal)closeModal()};
    }

    function openAreasSection(){document.querySelectorAll('.admin-section').forEach(s=>s.classList.toggle('active',s.id==='section-areas'));document.querySelectorAll('.nav-item').forEach(b=>b.classList.remove('active'));q('areasNavBtn')?.classList.add('active');if(q('sectionTitle'))q('sectionTitle').textContent='المناطق والقرى';loadAreas();window.lucide?.createIcons();window.scrollTo({top:0,behavior:'smooth'})}

    async function loadAreas(){const {data,error}=await dbAreas.from('service_areas').select('id,code,name_ar,area_type,parent_id,governorate,is_active,sort_order,source_note,latitude,longitude,created_at').order('sort_order').order('name_ar');if(error){toast('تعذر تحميل المناطق: '+error.message);return}areas=data||[];render()}
    function depth(a,map){let d=0,p=a.parent_id,g=0;while(p&&map[p]&&g++<8){d++;p=map[p].parent_id}return d}
    function render(){const tree=q('areasTree');if(!tree)return;const term=(q('areaSearch')?.value||'').trim().toLowerCase(),type=q('areaTypeFilter')?.value||'all';const map=Object.fromEntries(areas.map(a=>[a.id,a]));const children={};for(const a of areas)(children[a.parent_id||'root']??=[]).push(a);Object.values(children).forEach(arr=>arr.sort((a,b)=>(a.sort_order-b.sort_order)||a.name_ar.localeCompare(b.name_ar,'ar')));
      q('areaStatAll').textContent=areas.length.toLocaleString('ar-IQ');q('areaStatDistrict').textContent=areas.filter(a=>a.area_type==='district').length.toLocaleString('ar-IQ');q('areaStatSubdistrict').textContent=areas.filter(a=>a.area_type==='subdistrict').length.toLocaleString('ar-IQ');q('areaStatVillage').textContent=areas.filter(a=>['village','neighborhood'].includes(a.area_type)).length.toLocaleString('ar-IQ');
      const ordered=[];const walk=(pid)=>{for(const a of children[pid]||[]){ordered.push(a);walk(a.id)}};walk('root');for(const a of areas)if(!ordered.includes(a))ordered.push(a);
      const rows=ordered.filter(a=>(type==='all'||a.area_type===type)&&(!term||a.name_ar.toLowerCase().includes(term)||(map[a.parent_id]?.name_ar||'').toLowerCase().includes(term)));
      if(!rows.length){tree.innerHTML='<div class="area-empty">لا توجد نتائج.</div>';return}
      tree.innerHTML=rows.map(a=>{const d=Math.min(depth(a,map),3),parent=map[a.parent_id];return `<article class="area-row area-indent-${d} ${a.is_active?'':'inactive'}"><div class="area-main"><div class="area-title"><strong>${esc(a.name_ar)}</strong><span class="area-kind">${esc(kindLabel[a.area_type]||a.area_type)}</span>${a.is_active?'':'<span class="badge red">موقوفة</span>'}</div><div class="area-meta"><span>${parent?'تابعة لـ '+esc(parent.name_ar):'جذر التغطية'}</span>${a.latitude!=null&&a.longitude!=null?`<span>📍 ${Number(a.latitude).toFixed(4)}, ${Number(a.longitude).toFixed(4)}</span>`:''}</div></div><div class="area-actions"><button class="area-add-child" data-add-child="${a.id}">+ تابع</button><button data-edit-area="${a.id}">تعديل</button><button data-toggle-area="${a.id}">${a.is_active?'إيقاف':'تفعيل'}</button><button class="area-delete" data-delete-area="${a.id}">حذف</button></div></article>`}).join('');
      tree.querySelectorAll('[data-add-child]').forEach(b=>b.onclick=()=>openModal(null,b.dataset.addChild));tree.querySelectorAll('[data-edit-area]').forEach(b=>b.onclick=()=>openModal(b.dataset.editArea));tree.querySelectorAll('[data-toggle-area]').forEach(b=>b.onclick=()=>toggleArea(b.dataset.toggleArea));tree.querySelectorAll('[data-delete-area]').forEach(b=>b.onclick=()=>deleteArea(b.dataset.deleteArea));
    }

    function descendantIds(id){const out=new Set();let changed=true;while(changed){changed=false;for(const a of areas)if(a.parent_id&&(a.parent_id===id||out.has(a.parent_id))&&!out.has(a.id)){out.add(a.id);changed=true}}return out}
    async function openModal(id=null,parentId=null){editId=id;const a=id?areas.find(x=>x.id===id):null;q('areaModalTitle').textContent=a?'تعديل المنطقة':'إضافة منطقة';q('areaName').value=a?.name_ar||'';q('areaType').value=a?.area_type||(parentId?'village':'village');q('areaSort').value=a?.sort_order??0;q('areaActive').checked=a?.is_active??true;q('areaSource').value=a?.source_note||'';q('areaLat').value=a?.latitude??'';q('areaLng').value=a?.longitude??'';
      const blocked=id?descendantIds(id):new Set();const options=areas.filter(x=>x.id!==id&&!blocked.has(x.id));q('areaParent').innerHTML='<option value="">بدون أب</option>'+options.map(x=>`<option value="${x.id}">${esc(x.name_ar)} · ${esc(kindLabel[x.area_type]||x.area_type)}</option>`).join('');q('areaParent').value=a?.parent_id||parentId||'';q('areaModal').classList.remove('hidden');document.body.style.overflow='hidden';await initMap(a);}
    function closeModal(){q('areaModal').classList.add('hidden');document.body.style.overflow='';editId=null;if(map){map.remove();map=null;marker=null}}
    async function initMap(a){await ensureLeaflet();if(!window.L)return;const lat=Number(a?.latitude||35.47),lng=Number(a?.longitude||43.25);map=L.map('areaMap').setView([lat,lng],a?.latitude?14:10);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap'}).addTo(map);if(a?.latitude!=null&&a?.longitude!=null)marker=L.marker([lat,lng]).addTo(map);map.on('click',e=>{q('areaLat').value=e.latlng.lat.toFixed(6);q('areaLng').value=e.latlng.lng.toFixed(6);if(marker)marker.setLatLng(e.latlng);else marker=L.marker(e.latlng).addTo(map)});setTimeout(()=>map.invalidateSize(),120)}
    async function saveArea(e){e.preventDefault();const name=q('areaName').value.trim();if(!name)return toast('اكتب اسم المنطقة');const payload={name_ar:name,area_type:q('areaType').value,parent_id:q('areaParent').value||null,is_active:q('areaActive').checked,sort_order:Number(q('areaSort').value||0),source_note:q('areaSource').value.trim()||null,latitude:q('areaLat').value===''?null:Number(q('areaLat').value),longitude:q('areaLng').value===''?null:Number(q('areaLng').value),updated_at:new Date().toISOString()};let error;if(editId){({error}=await dbAreas.from('service_areas').update(payload).eq('id',editId))}else{payload.code='area_'+Date.now().toString(36)+'_'+Math.random().toString(36).slice(2,6);({error}=await dbAreas.from('service_areas').insert(payload))}if(error)return toast('تعذر الحفظ: '+error.message);toast(editId?'تم تعديل المنطقة':'تمت إضافة المنطقة');closeModal();loadAreas()}
    async function toggleArea(id){const a=areas.find(x=>x.id===id);if(!a)return;const {error}=await dbAreas.from('service_areas').update({is_active:!a.is_active,updated_at:new Date().toISOString()}).eq('id',id);if(error)return toast(error.message);toast(!a.is_active?'تم تفعيل المنطقة':'تم إيقاف المنطقة');loadAreas()}
    async function deleteArea(id){const a=areas.find(x=>x.id===id);if(!a)return;const kids=areas.filter(x=>x.parent_id===id);if(kids.length)return toast(`لا يمكن حذف ${a.name_ar} لأنها تحتوي ${kids.length} منطقة تابعة`);if(!confirm(`حذف "${a.name_ar}" نهائياً؟`))return;const {error}=await dbAreas.from('service_areas').delete().eq('id',id);if(error)return toast('تعذر الحذف لأنها مستخدمة في حسابات أو طلبات، أو بسبب: '+error.message);toast('تم حذف المنطقة');loadAreas()}

    await loadAreas();window.lucide?.createIcons();
  });
})();