const {SUPABASE_URL,SUPABASE_KEY}=window.JEEBLI_CONFIG;
const db=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
const $=id=>document.getElementById(id);
const authView=$('authView'),appView=$('appView'),logoutBtn=$('logoutBtn'),toast=$('toast');
let currentUser=null,selectedService='taxi',rideChannel=null,map=null,pickMode='pickup';
let pickupMarker=null,destinationMarker=null,routeLine=null,currentQuote=null,activeRide=null;

function notify(message){toast.textContent=message;toast.classList.remove('hidden');clearTimeout(window.__toastTimer);window.__toastTimer=setTimeout(()=>toast.classList.add('hidden'),3300)}
function setBusy(form,busy){const btn=form.querySelector('button[type="submit"]');if(!btn)return;btn.disabled=busy;btn.style.opacity=busy?'.65':'1'}
function escapeHtml(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]))}
function statusLabel(status){return({requested:'تم الطلب',searching:'جاري البحث عن سائق',accepted:'السائق قبل الرحلة',driver_arrived:'السائق وصل',in_progress:'الرحلة جارية',completed:'مكتملة',cancelled:'ملغاة'})[status]||status}
function serviceLabel(service){return({taxi:'تكسي',private:'خصوصي',delivery:'توصيل',intercity:'بين المحافظات',cargo:'حمل'})[service]||service}
function money(v){return Number(v||0).toLocaleString('ar-IQ')+' د.ع'}
function statusProgress(status){return({requested:12,searching:27,accepted:48,driver_arrived:65,in_progress:82,completed:100,cancelled:100})[status]||8}

function initMap(){if(map)return;map=L.map('map',{zoomControl:true}).setView([35.47,43.25],11);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; OpenStreetMap'}).addTo(map);map.on('click',e=>setMapPoint(pickMode,e.latlng.lat,e.latlng.lng,true))}
function setPickMode(mode){pickMode=mode;$('pickPickupBtn').classList.toggle('active',mode==='pickup');$('pickDestinationBtn').classList.toggle('active',mode==='destination')}
function setMapPoint(mode,lat,lng,center=false){const isPickup=mode==='pickup',latInput=$(isPickup?'pickupLat':'destinationLat'),lngInput=$(isPickup?'pickupLng':'destinationLng'),addressInput=$(isPickup?'pickupAddress':'destinationAddress');latInput.value=Number(lat).toFixed(6);lngInput.value=Number(lng).toFixed(6);if(!addressInput.value.trim())addressInput.value=isPickup?'موقع الانطلاق المحدد على الخريطة':'الوجهة المحددة على الخريطة';const marker=L.marker([lat,lng],{draggable:true}).addTo(map);marker.bindTooltip(isPickup?'الانطلاق':'الوجهة',{direction:'top'});marker.on('dragend',ev=>{const p=ev.target.getLatLng();latInput.value=p.lat.toFixed(6);lngInput.value=p.lng.toFixed(6);updateRouteLine();resetQuote()});if(isPickup){if(pickupMarker)map.removeLayer(pickupMarker);pickupMarker=marker;setPickMode('destination')}else{if(destinationMarker)map.removeLayer(destinationMarker);destinationMarker=marker}if(center)map.panTo([lat,lng]);updateRouteLine();resetQuote()}
function updateRouteLine(){if(routeLine){map.removeLayer(routeLine);routeLine=null}if(!pickupMarker||!destinationMarker)return;const pts=[pickupMarker.getLatLng(),destinationMarker.getLatLng()];routeLine=L.polyline(pts,{weight:5,opacity:.8,dashArray:'8 8'}).addTo(map);map.fitBounds(L.latLngBounds(pts).pad(.28))}
function resetQuote(){currentQuote=null;$('quoteCard').classList.add('hidden');$('quoteState').textContent='بانتظار الحساب'}

async function calculateQuote(showMessage=true){if(!currentUser)return notify('سجّل الدخول أولاً');const pickupLat=Number($('pickupLat').value),pickupLng=Number($('pickupLng').value),destinationLat=Number($('destinationLat').value),destinationLng=Number($('destinationLng').value);if(!Number.isFinite(pickupLat)||!Number.isFinite(pickupLng)||!Number.isFinite(destinationLat)||!Number.isFinite(destinationLng)){notify('حدد موقع الانطلاق والوجهة على الخريطة أولاً');return null}$('quoteState').textContent='جاري الحساب...';const {data,error}=await db.rpc('estimate_ride_quote',{p_service_type:selectedService,p_pickup_lat:pickupLat,p_pickup_lng:pickupLng,p_destination_lat:destinationLat,p_destination_lng:destinationLng});if(error||!data?.length){$('quoteState').textContent='تعذر الحساب';notify('تعذر حساب السعر حالياً');return null}currentQuote=data[0];$('quoteDistance').textContent=`${Number(currentQuote.distance_km).toLocaleString('ar-IQ',{maximumFractionDigits:2})} كم`;$('quoteFare').textContent=money(currentQuote.estimated_fare);$('quoteCard').classList.remove('hidden');$('quoteState').textContent='تم حساب السعر';if(showMessage)notify('تم حساب السعر التقديري');return currentQuote}

async function showApp(user){currentUser=user;authView.classList.add('hidden');appView.classList.remove('hidden');logoutBtn.classList.remove('hidden');const {data}=await db.from('profiles').select('full_name').eq('id',user.id).maybeSingle();$('userName').textContent=data?.full_name||user.user_metadata?.full_name||'مستخدم جيبلي';initMap();setTimeout(()=>map.invalidateSize(),120);await loadRides();subscribeToRides()}
function showAuth(){currentUser=null;activeRide=null;appView.classList.add('hidden');authView.classList.remove('hidden');logoutBtn.classList.add('hidden');if(rideChannel){db.removeChannel(rideChannel);rideChannel=null}}
function renderActiveRide(ride){activeRide=ride||null;const panel=$('activeRidePanel');if(!ride||['completed','cancelled'].includes(ride.status)){panel.classList.add('hidden');return}panel.classList.remove('hidden');$('activeRideStatus').textContent=statusLabel(ride.status);$('activeRideId').textContent='#'+ride.id.slice(0,8).toUpperCase();$('progressBar').style.width=statusProgress(ride.status)+'%';$('activeRoute').innerHTML=`<div>🟢 <strong>من:</strong> ${escapeHtml(ride.pickup_address)}</div><div>📍 <strong>إلى:</strong> ${escapeHtml(ride.destination_address)}</div><div>💰 <strong>التقدير:</strong> ${money(ride.estimated_fare)} · ${Number(ride.distance_km||0).toLocaleString('ar-IQ')} كم</div>`;$('cancelRideBtn').classList.toggle('hidden',!['requested','searching'].includes(ride.status))}
async function loadRides(){if(!currentUser)return;const {data,error}=await db.from('rides').select('id,service_type,status,pickup_address,destination_address,estimated_fare,distance_km,currency,requested_at').eq('customer_id',currentUser.id).order('requested_at',{ascending:false}).limit(20);if(error){notify('تعذر تحميل الرحلات');return}renderActiveRide(data?.find(r=>!['completed','cancelled'].includes(r.status))||null);const list=$('ridesList');if(!data?.length){list.innerHTML='<div class="empty">ما عندك رحلات بعد. أول طلب راح يظهر هنا.</div>';return}list.innerHTML=data.map(r=>`<article class="ride-item"><div class="ride-top"><div><strong>${serviceLabel(r.service_type)}</strong><div class="ride-id">#${r.id.slice(0,8).toUpperCase()}</div></div><div class="ride-status">${statusLabel(r.status)}</div></div><div class="route"><div>🟢 <span>من:</span> ${escapeHtml(r.pickup_address)}</div><div>📍 <span>إلى:</span> ${escapeHtml(r.destination_address)}</div></div><div class="ride-meta"><span>${Number(r.distance_km||0).toLocaleString('ar-IQ')} كم</span><strong>${money(r.estimated_fare)}</strong></div></article>`).join('')}
function subscribeToRides(){if(rideChannel)db.removeChannel(rideChannel);rideChannel=db.channel(`rides-${currentUser.id}`).on('postgres_changes',{event:'*',schema:'public',table:'rides',filter:`customer_id=eq.${currentUser.id}`},payload=>{loadRides();if(payload.eventType==='UPDATE')notify('تحديث جديد على حالة رحلتك')}).subscribe()}

document.querySelectorAll('.tab').forEach(tab=>tab.addEventListener('click',()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));tab.classList.add('active');$('loginForm').classList.toggle('active-form',tab.dataset.tab==='login');$('signupForm').classList.toggle('active-form',tab.dataset.tab==='signup')}));
document.querySelectorAll('.service-card').forEach(card=>card.addEventListener('click',()=>{document.querySelectorAll('.service-card').forEach(x=>x.classList.remove('selected'));card.classList.add('selected');selectedService=card.dataset.service;resetQuote();if(pickupMarker&&destinationMarker)calculateQuote(false)}));
$('pickPickupBtn').addEventListener('click',()=>setPickMode('pickup'));$('pickDestinationBtn').addEventListener('click',()=>setPickMode('destination'));
$('signupForm').addEventListener('submit',async e=>{e.preventDefault();setBusy(e.currentTarget,true);const full_name=$('signupName').value.trim(),phone=$('signupPhone').value.trim();const {data,error}=await db.auth.signUp({email:$('signupEmail').value.trim(),password:$('signupPassword').value,options:{data:{full_name,phone}}});setBusy(e.currentTarget,false);if(error)return notify(error.message);if(data.session){notify('تم إنشاء الحساب بنجاح');showApp(data.user)}else notify('تم إنشاء الحساب. تحقق من بريدك لتأكيده ثم سجّل الدخول.')});
$('loginForm').addEventListener('submit',async e=>{e.preventDefault();setBusy(e.currentTarget,true);const {data,error}=await db.auth.signInWithPassword({email:$('loginEmail').value.trim(),password:$('loginPassword').value});setBusy(e.currentTarget,false);if(error)return notify('بيانات الدخول غير صحيحة أو الحساب غير مؤكد');notify('تم تسجيل الدخول');showApp(data.user)});
logoutBtn.addEventListener('click',async()=>{await db.auth.signOut();showAuth();notify('تم تسجيل الخروج')});
$('useLocationBtn').addEventListener('click',()=>{if(!navigator.geolocation)return notify('المتصفح لا يدعم تحديد الموقع');navigator.geolocation.getCurrentPosition(pos=>{setMapPoint('pickup',pos.coords.latitude,pos.coords.longitude,true);$('pickupAddress').value='موقعي الحالي';map.setZoom(16);notify('تم تحديد موقعك الحالي')},()=>notify('تعذر الوصول إلى موقعك. فعّل إذن الموقع.'),{enableHighAccuracy:true,timeout:10000})});
$('previewBtn').addEventListener('click',()=>calculateQuote(true));
$('rideForm').addEventListener('submit',async e=>{e.preventDefault();if(!currentUser)return notify('سجّل الدخول أولاً');if(activeRide&&!['completed','cancelled'].includes(activeRide.status))return notify('عندك طلب فعال حالياً. أكمله أو ألغِه أولاً.');const quote=currentQuote||await calculateQuote(false);if(!quote)return;if(!$('pickupAddress').value.trim()||!$('destinationAddress').value.trim())return notify('اكتب وصف الانطلاق والوجهة');if(!window.confirm(`تأكيد طلب ${serviceLabel(selectedService)}\nالمسافة: ${quote.distance_km} كم\nالسعر التقديري: ${money(quote.estimated_fare)}`))return;setBusy(e.currentTarget,true);const payload={customer_id:currentUser.id,service_type:selectedService,status:'requested',pickup_address:$('pickupAddress').value.trim(),pickup_lat:Number($('pickupLat').value),pickup_lng:Number($('pickupLng').value),destination_address:$('destinationAddress').value.trim(),destination_lat:Number($('destinationLat').value),destination_lng:Number($('destinationLng').value),notes:$('rideNotes').value.trim()||null};const {data,error}=await db.from('rides').insert(payload).select('id,status,service_type,pickup_address,destination_address,estimated_fare,distance_km,currency,requested_at').single();setBusy(e.currentTarget,false);if(error)return notify(`تعذر إنشاء الطلب: ${error.message}`);activeRide=data;renderActiveRide(data);notify('تم إرسال طلبك وجاري البحث عن سائق');await loadRides()});
$('cancelRideBtn').addEventListener('click',async()=>{if(!activeRide||!['requested','searching'].includes(activeRide.status))return;if(!window.confirm('هل تريد إلغاء هذا الطلب؟'))return;const {error}=await db.from('rides').update({status:'cancelled'}).eq('id',activeRide.id).eq('customer_id',currentUser.id);if(error)return notify('تعذر إلغاء الطلب');notify('تم إلغاء الطلب');await loadRides()});
$('refreshRidesBtn').addEventListener('click',loadRides);
db.auth.onAuthStateChange((_event,session)=>{if(session?.user&&!currentUser)showApp(session.user);if(!session?.user&&currentUser)showAuth()});
(async()=>{const {data:{session}}=await db.auth.getSession();session?.user?showApp(session.user):showAuth()})();
